stages:
  - build
  - deploy

.wheel:
  stage: build
  tags:
    - linux
  script:
    - ./ci/build-wheels.sh ${CI_PROJECT_DIR} ${CI_PROJECT_DIR}/wheelhouse
  artifacts:
    paths:
      - wheelhouse/*.whl

wheel-x86:
  extends: .wheel
  image: quay.io/pypa/manylinux_2_24_x86_64
  variables:
    PLAT: manylinux_2_24_x86_64

wheel-aarch64:
  extends: .wheel
  image: quay.io/pypa/manylinux_2_24_aarch64
  variables:
    PLAT: manylinux_2_24_aarch64

src:
  stage: build
  tags:
    - linux
  image: python:3.7
  before_script:
    - python -m pip install build
  script:
    - python -m build --sdist --outdir dist .
  artifacts:
    paths:
      - dist/*.tar.gz

.wheel-win:
  stage: build
  tags:
    - windows
  before_script:
    # https://gitlab.com/gitlab-org/ci-cd/shared-runners/images/gcp/windows-containers/-/issues/13
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install python3 --version=$PYTHON_VERSION --yes --force --no-progress
    - refreshenv
  script:
    - python --version
    - python -m pip install build
    - python -m build --wheel --outdir dist .
  artifacts:
    paths:
      - dist\ft4222-*.whl

wheel-win-3.7:
  extends: .wheel-win
  variables:
    PYTHON_VERSION: "3.7"

wheel-win-3.8:
  extends: .wheel-win
  variables:
    PYTHON_VERSION: "3.8"

wheel-win-3.9:
  extends: .wheel-win
  variables:
    PYTHON_VERSION: "3.9"

wheel-win-3.10:
  extends: .wheel-win
  variables:
    PYTHON_VERSION: "3.10"

pypi:
  stage: deploy
  image: python:3.7-slim
  before_script:
    - pip install twine
  script:
    - twine upload dist/*
    - twine upload wheelhouse/*
  only:
    - tags

pages:
  stage: build
  tags:
    - linux
  image: python:3.7-alpine
  before_script:
    - apk --no-cache add build-base
    - echo "manylinux1_compatible = True" > $(dirname /usr/local/lib/python3.*/.)/site-packages/_manylinux.py
    - pip install cython
  script:
  - pip install sphinx m2r2 sphinx-rtd-theme
  - python setup.py install
  - make -C doc html
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
