default:
  image: python:3.7-alpine
  before_script:
    - apk --no-cache add build-base
    - echo "manylinux1_compatible = True" > $(dirname /usr/local/lib/python3.*/.)/site-packages/_manylinux.py
    - pip install cython

.wheel:
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/ft4222-*.whl

wheel-3.6:
  image: python:3.6-alpine
  extends: .wheel

wheel-3.7:
  image: python:3.7-alpine
  extends: .wheel

wheel-3.8:
  image: python:3.8-alpine
  extends: .wheel

pages:
  script:
  - pip install sphinx
  - python setup.py install
  - make -C doc html
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
