image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add build-base cython
  - build-linux.sh
  - cd doc
  - doc-linux.sh
  - mv _build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
