image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev
  - pip install sphinx
  - apk --no-cache add build-base cython cython-dev
  - CFLAGS=-Ilinux LDFLAGS=-Llinux/build-x86_64/ python setup.py build_ext -i
  - LD_LIBRARY_PATH=linux/build-x86_64/. PYTHONPATH=. make -C doc html 
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
